export const sampleData = [
    {
    id: 0,
    location: "CTD HQ",
    name: "Dark Knight",
    designation: "System Admin",
    phone: "995613XXXX",
    email: "Knight007@gmail.com",
  },{
    id: 1,
    location: "Agra",
    name: "Arpit Sachan",
    designation: "Technical Support Engineer",
    phone: "9026858921",
    email: "arpitsoftware08@gmail.com",
  },
  {
    id: 2,
    location: "Aligarh",
    name: "Manoj Yadav",
    designation: "Technical Support Engineer",
    phone: "9456060714",
    email: "manoj123yadavbly@gmail.com",
  },
  {
    id: 3,
    location: "Ambedkarnagar",
    name: "Pawan Charasia",
    designation: "Technical Support Engineer",
    phone: "7007829746",
    email: "chaurasiyapawan789@gmail.com",
  },
  {
    id: 4,
    location: "Amethi",
    name: "Prashant Kumar Singh",
    designation: "Technical Support Engineer",
    phone: "9936436700",
    email: "prashantsinghcs3@gmail.com",
  },
  {
    id: 5,
    location: "Amroha",
    name: "Yogesh Verma",
    designation: "Technical Support Engineer",
    phone: "9927538162",
    email: "yogeshsbibank@gmial.com",
  },
  {
    id: 6,
    location: "Auraiya",
    name: "Vivek Kumar",
    designation: "Technical Support Engineer",
    phone: "9891407981",
    email: "vivekpalinfo@gmail.com",
  },
  {
    id: 7,
    location: "Azamgrah",
    name: "Dayanand Singh",
    designation: "Technical Support Engineer",
    phone: "7007456722",
    email: "readdysingh@gmail.com",
  },
  {
    id: 8,
    location: "Badaun",
    name: "Naipal Singh",
    designation: "Technical Support Engineer",
    phone: "7500360563",
    email: "naipalsingh@rocketmail.com",
  },
  {
    id: 9,
    location: "Baghpat",
    name: "Jagdeep Tomar",
    designation: "Technical Support Engineer",
    phone: "9675168468",
    email: "jagdeeptomar2@gmail.com",
  },
  {
    id: 10,
    location: "Bahraich",
    name: "Brijendra Kumar Upadhyay",
    designation: "Technical Support Engineer",
    phone: "8707877372",
    email: "upadhyay.bk11@gmail.com",
  },

  {
    id: 11,
    location: "Ballia",
    name: "Ajay Kumar",
    designation: "Technical Support Engineer",
    phone: "9452107628",
    email: "ajaykumarkushwaha4@gmail.com",
  },
  {
    id: 12,
    location: "Balrampur",
    name: "Abhishek Srivastav",
    designation: "Technical Support Engineer",
    phone: "7905965114",
    email: "aman.srivastava72@gmail.com",
  },
  {
    id: 13,
    location: "Banda",
    name: "Ashish Kumar Singh",
    designation: "Technical Support Engineer",
    phone: "9506249004",
    email: "chauhan.ashish28@gmail.com",
  },
  {
    id: 14,
    location: "Barabanki",
    name: "Ankit Sharma",
    designation: "Technical Support Engineer",
    phone: "6386091427",
    email: "sharmaankit13917@gmail.com",
  },
  {
    id: 15,
    location: "Baraut",
    name: "Atul Kumar Pandey",
    designation: "Technical Support Engineer",
    phone: "9554227940",
    email: "atulmpandey@gmail.com",
  },
  {
    id: 16,
    location: "Bareilly",
    name: "Abhishek Srivastava",
    designation: "Technical Support Engineer",
    phone: "8273593451",
    email: "erabhi.srivastava@gmail.com",
  },
  {
    id: 17,
    location: "Basti",
    name: "Atul Kumar Yadav",
    designation: "Technical Support Engineer",
    phone: "9457132524",
    email: "atul.yadav96@gmail.com",
  },
  {
    id: 18,
    location: "Bhadoi",
    name: "Amit Srivastava",
    designation: "Technical Support Engineer",
    phone: "8381826752",
    email: "getamitsrivastav90@gmail.com",
  },
  {
    id: 19,
    location: "Bijnor",
    name: "Sachin Pratap Singh",
    designation: "Technical Support Engineer",
    phone: "9458010428",
    email: "pratap.sachin3@gmail.com",
  },
  {
    id: 20,
    location: "Bulandshar",
    name: "Yashveer Singh",
    designation: "Technical Support Engineer",
    phone: "9758553397",
    email: "shive.yesh20@gmail.com",
  },

  {
    id: 21,
    location: "Chandausi",
    name: "Abhinav Srivastava",
    designation: "Technical Support Engineer",
    phone: "8299431679",
    email: "abhinav.srivastava04@gmail.com",
  },
  {
    id: 22,
    location: "Chandpur",
    name: "Pramod Kumar",
    designation: "Technical Support Engineer",
    phone: "9458250669",
    email: "pramodchauhanom@gmail.com",
  },
  {
    id: 23,
    location: "CTD HQ",
    name: "Rajeev Kumar Dwivedi",
    designation: "Project Manager",
    phone: "8090015316",
    email: "Rajeev.netsoft@gmail.com",
  },
  {
    id: 24,
    location: "CTD HQ",
    name: "Vikas Singh",
    designation: "Solution Architect",
    phone: "9125711817",
    email: "vikas_basti008@rediffmail.com",
  },
  {
    id: 25,
    location: "CTD HQ",
    name: "Brijesh Kumar Srivastava",
    designation: "Database Administrator",
    phone: "9169647311",
    email: "brijesh.srivastava05@gmail.com",
  },
  {
    id: 26,
    location: "CTD HQ",
    name: "Ramesh Kumar",
    designation: "Lead Network Administrator",
    phone: "9935903990",
    email: "ramesh_raj003@rediffmail.com",
  },
  {
    id: 27,
    location: "CTD HQ",
    name: "Harish Kushwaha",
    designation: "Technical Support Engineer",
    phone: "9956137719",
    email: "kushwahaharish023@gmail.com",
  },
  {
    id: 28,
    location: "CTD HQ",
    name: "Kalyan Singh",
    designation: "Sr. Software Developer",
    phone: "8052558468",
    email: "kalyansinghrajput236@gmail.com",
  },
  {
    id: 29,
    location: "CTD HQ",
    name: "Anup Kumar",
    designation: "Software Developer",
    phone: "8601137643",
    email: "anupkumarpal0000@gmail.com",
  },
  {
    id: 30,
    location: "CTD HQ",
    name: "Abhishek Yadav",
    designation: "Software Developer",
    phone: "8896724354",
    email: "abhishekyadav10111998@gmail.com",
  },

  {
    id: 31,
    location: "CTD HQ",
    name: "Himanshu Rajput",
    designation: "Technical Support Engineer",
    phone: "8881018951",
    email: "himanshurajput37043@gmail.com",
  },
  {
    id: 32,
    location: "CTD HQ",
    name: "Neeraj Bajpai",
    designation: "Sr. Software Developer",
    phone: "9795865225",
    email: "93neerajbajpai@gmail.com",
  },
  {
    id: 33,
    location: "CTD HQ",
    name: "Ankit Raj Gupta",
    designation: "Sr. Software Developer",
    phone: "8726946456",
    email: "gankit367@gmail.com",
  },
  {
    id: 34,
    location: "CTD HQ",
    name: "Ankit Srivastava",
    designation: "Sr. Software Developer",
    phone: "8924929162",
    email: "ankitsrv11@gmail.com",
  },
  {
    id: 35,
    location: "CTD HQ",
    name: "Prashant Bhaskar",
    designation: "Technical Support Engineer",
    phone: "8948890692",
    email: "prashantbhaskar9161@gmail.com",
  },
  {
    id: 36,
    location: "CTD HQ",
    name: "Rakesh Mishra",
    designation: "Software Developer",
    phone: "7905441819",
    email: "rakesh019mishra@gmail.com",
  },
  {
    id: 37,
    location: "CTD HQ",
    name: "Ankit Mishra",
    designation: "Software Developer",
    phone: "9839053434",
    email: "ankitmishra609@gmail.com",
  },
  {
    id: 38,
    location: "CTD HQ",
    name: "Vartika Gupta",
    designation: "Sr. Software Developer",
    phone: "8707818422",
    email: "gvartika29@gmail.com",
  },
  {
    id: 39,
    location: "CTD HQ",
    name: "Prashu Gupta",
    designation: "Software Developer",
    phone: "9140957816",
    email: "prashugupta914@gmail.com",
  },

  {
    id: 40,
    location: "CTD HQ",
    name: "Adarsh Gupta",
    designation: "Technical Support Engineer",
    email: "adarshgupta2784@gmail.com",
    phone: "9696716250",
  },
  {
    id: 41,
    location: "CTD HQ",
    name: "Yogesh Pratap Singh",
    designation: "Technical Support Engineer",
    email: "yogeshsngh139@gmail.com",
    phone: "7836037139",
  },
  {
    id: 42,
    location: "CTD HQ",
    name: "Ashish Maurya",
    designation: "EMS/NMS Tool Administrator",
    email: "asmaurya2016@gmail.com",
    phone: "7052723321",
  },
  {
    id: 43,
    location: "CTD HQ",
    name: "Ashok Kumar Singh",
    designation: "Technical Support Engineer",
    email: "2011aksingh@gmail.com",
    phone: "8874072316",
  },
  {
    id: 44,
    location: "CTD HQ",
    name: "Aman Sonkar",
    designation: "Sr. Software Developer",
    email: "ai.amansonkar@gmail.com",
    phone: "7071211404",
  },
  {
    id: 45,
    location: "CTD HQ",
    name: "Pragya Mishra",
    designation: "Data Analyst",
    email: "pragyam28@gmail.com",
    phone: "9451430711",
  },
  {
    id: 46,
    location: "CTD HQ",
    name: "Ajeet Kumar Mourya",
    designation: "Software Developer",
    email: "Ajeetkumar1711@gmail.com",
    phone: "8318887220",
  },
  {
    id: 47,
    location: "CTD HQ",
    name: "Sudheer Modanwal",
    designation: "Data Analyst",
    email: "sudhirmodanwal49@gmail.com",
    phone: "8874227484",
  },
  {
    id: 48,
    location: "CTD HQ",
    name: "Akhilesh Kumar",
    designation: "Technical Support Engineer",
    email: "akhileshjaiswal222@gmail.com",
    phone: "7800596092",
  },
  {
    id: 49,
    location: "Deoria",
    name: "Prakash Kumar Sharma",
    designation: "Technical Support Engineer",
    email: "prakasharma92@gmail.com",
    phone: "9984358135",
  },
  {
    id: 50,
    location: "Etah",
    name: "Shivendra Kumar",
    designation: "Technical Support Engineer",
    email: "Shuklashivendra1981@gmail.com",
    phone: "9456251148",
  },
  {
    id: 51,
    location: "Etawah",
    name: "Vipin Kumar",
    designation: "Technical Support Engineer",
    email: "vipin.lucky88@gmail.com",
    phone: "7007208895",
  },
  {
    id: 52,
    location: "Faizabad",
    name: "Vivek Kumar Verma",
    designation: "Technical Support Engineer",
    email: "vivek.pseudo@gmail.com",
    phone: "9455593782",
  },
  {
    id: 53,
    location: "Farukhabad",
    name: "Rajan Shakya",
    designation: "Technical Support Engineer",
    email: "rajanshakya12@gmail.com",
    phone: "7317811900",
  },
  {
    id: 54,
    location: "Fatehpur",
    name: "Vikesh Kumar Gupta",
    designation: "Technical Support Engineer",
    email: "vikesh.gta@gmail.com",
    phone: "7376267192",
  },
  {
    id: 55,
    location: "Firozabad",
    name: "Harsh Vardhan",
    designation: "Technical Support Engineer",
    email: "harsh_2881@yahoo.co.in",
    phone: "8077731866",
  },
  {
    id: 56,
    location: "Gautam Budh Nagar",
    name: "Prabhakar Kumar",
    designation: "Technical Support Engineer",
    email: "prabhakershakya72@gmail.com",
    phone: "8299088952",
  },
  {
    id: 57,
    location: "Ghaziabad",
    name: "Vijay Pratap Singh",
    designation: "Technical Support Engineer",
    email: "vijaypratap.it@gmail.com",
    phone: "9971783749",
  },
  {
    id: 58,
    location: "Ghazipur",
    name: "Praveen Pandey",
    designation: "Technical Support Engineer",
    email: "saloyat@gmail.com",
    phone: "7581031561",
  },
  {
    id: 59,
    location: "Gonda",
    name: "Dipendra Singh",
    designation: "Technical Support Engineer",
    email: "dipendra370@gmail.com",
    phone: "8707729161",
  },
  {
    id: 60,
    location: "Gorakhpur",
    name: "Md. Ehteshamul Haque",
    designation: "Technical Support Engineer",
    email: "fommy.haq@gmail.com",
    phone: "9807526743",
  },
  {
    id: 61,
    location: "Gulawati",
    name: "Pravesh Giri",
    designation: "Technical Support Engineer",
    email: "praveshbsr07@gmail.com",
    phone: "8218407176",
  },
  {
    id: 62,
    location: "Hamirpur",
    name: "Saurabh Pandey",
    designation: "Technical Support Engineer",
    email: "saurabhpandey6607@gmail.com",
    phone: "8299186501",
  },
  {
    id: 63,
    location: "Hapur",
    name: "Deepak Tomar",
    designation: "Technical Support Engineer",
    email: "dpktomar399@gmail.com",
    phone: "8868057512",
  },
  {
    id: 64,
    location: "Hardoi",
    name: "Vivek Kumar Mishra",
    designation: "Technical Support Engineer",
    email: "vivekmishra512@gmail.com",
    phone: "9643159012",
  },
  {
    id: 65,
    location: "Hathras",
    name: "Rohit Kumar",
    designation: "Technical Support Engineer",
    email: "rhtdixit9@gmail.com",
    phone: "9759595556",
  },
  {
    id: 66,
    location: "Jaunpur",
    name: "Deepak Yadav",
    designation: "Technical Support Engineer",
    email: "deepak.engg84@gmail.com",
    phone: "7376028209",
  },
  {
    id: 67,
    location: "Jhansi",
    name: "Ram Chaturvedi",
    designation: "Technical Support Engineer",
    email: "ramchaturvedi.2010@gmail.com",
    phone: "8840376105",
  },
  {
    id: 68,
    location: "Kannauj",
    name: "Sandeep Kumar",
    designation: "Technical Support Engineer",
    email: "sandeeptechnical1@gmail.com",
    phone: "8707408193",
  },
  {
    id: 69,
    location: "Kanpur Nagar",
    name: "Manoj Kumar Saini",
    designation: "Technical Support Engineer",
    email: "hellomksini@gmail.com",
    phone: "9005246958",
  },
  {
    id: 70,
    location: "Kanpur (Akhberpur)",
    name: "Yogesh Kumar Pandey",
    designation: "Technical Support Engineer",
    email: "ykpandey222333@gmail.com",
    phone: "8887746609",
  },
  {
    id: 71,
    location: "Kasganj",
    name: "Ravendra Yadav",
    designation: "Technical Support Engineer",
    email: "ravendray377@gmail.com",
    phone: "9719626621",
  },
  {
    id: 72,
    location: "Kausambi",
    name: "Indrajeet Kumar Yadav",
    designation: "Technical Support Engineer",
    email: "indrajeetkumaryadav654@gmail.com",
    phone: "7903544588",
  },
  {
    id: 73,
    location: "Khatauli",
    name: "Ajay Kumar Singh",
    designation: "Technical Support Engineer",
    email: "akkajay500@gmail.com",
    phone: "7302917309",
  },
  {
    id: 74,
    location: "Khurza",
    name: "Praveen Kumar",
    designation: "Technical Support Engineer",
    email: "emailindiatoall@gmail.com",
    phone: "7830268214",
  },
  {
    id: 75,
    location: "Kushinagar",
    name: "Amit Kumar Singh",
    designation: "Technical Support Engineer",
    email: "ak.singh2086@gmail.com",
    phone: "9968949951",
  },
  {
    id: 76,
    location: "Lakhimpur",
    name: "Chanchal Kumar",
    designation: "Technical Support Engineer",
    email: "chanchal_k7@rediffmail.com",
    phone: "8010766058",
  },
  {
    id: 77,
    location: "Lalitpur",
    name: "Nakul Jha",
    designation: "Technical Support Engineer",
    email: "nakuljhansi2017@gmail.com",
    phone: "9971617455",
  },
  {
    id: 78,
    location: "Lucknow Mirabai Marg",
    name: "Neeraj Mishra",
    designation: "Technical Support Engineer",
    email: "neeraj.iise@gmail.com",
    phone: "8090465808",
  },
  {
    id: 79,
    location: "Lucknow Training Center",
    name: "Utkarsh Singh",
    designation: "Technical Support Engineer",
    email: "utkrshhh93@gmail.com",
    phone: "9918192277",
  },
  {
    id: 80,
    location: "Lucknow Training Center",
    name: "Sandeep Prajapati",
    designation: "Technical Support Engineer",
    email: "prajapatisan7@gmail.com",
    phone: "8418979763",
  },

  {
    id: 81,
    location: "Maharajganj",
    name: "Abhishek Srivastava",
    designation: "Technical Support Engineer",
    email: "abhishek86srivastav@gmail.com",
    phone: "7068851626",
  },
  {
    id: 82,
    location: "Mahoba",
    name: "Dharmesh Vishwakarma",
    designation: "Technical Support Engineer",
    email: "vishwakarma.dharmesh7@gmail.com",
    phone: "9179598214",
  },
  {
    id: 83,
    location: "Mainpuri",
    name: "Praval Pratap",
    designation: "Technical Support Engineer",
    email: "prawalpratap123@gmail.com",
    phone: "9410224070",
  },
  {
    id: 84,
    location: "Mathura (Kosi Kala)",
    name: "Nitin Kumar",
    designation: "Technical Support Engineer",
    email: "sunnybca2008@gmail.com",
    phone: "9897947654",
  },
  {
    id: 85,
    location: "Mathura (Krishna Nagar)",
    name: "Suraj Kumar",
    designation: "Technical Support Engineer",
    email: "surajgautambhakhar@gmail.com",
    phone: "7520092774",
  },
  {
    id: 86,
    location: "Mau",
    name: "Shailendra Maurya",
    designation: "Technical Support Engineer",
    email: "shailendramaurya1123@gmail.com",
    phone: "7052952051",
  },
  {
    id: 87,
    location: "Mawana",
    name: "Deepak Kumar",
    designation: "Technical Support Engineer",
    email: "dk5733202@gmail.com",
    phone: "8077081395",
  },
  {
    id: 88,
    location: "Meerut",
    name: "Kuldeep Kumar",
    designation: "Technical Support Engineer",
    email: "gunnukuldeep@gmail.com",
    phone: "9953193890",
  },
  {
    id: 89,
    location: "Mirzapur",
    name: "Kamlesh Kumar",
    designation: "Technical Support Engineer",
    email: "kumar.kamlesh51@gmail.com",
    phone: "9140577454",
  },
  {
    id: 90,
    location: "Modinagar",
    name: "Rahul Kumar",
    designation: "Technical Support Engineer",
    email: "rahul.k1291@gmail.com",
    phone: "8791328950",
  },
  {
    id: 91,
    location: "Moradabad",
    name: "Satendra Singh",
    designation: "Technical Support Engineer",
    email: "satendarsingh21@gmail.com",
    phone: "8077810647",
  },
  {
    id: 92,
    location: "Muzzafarnagar",
    name: "Neeraj Kumar Tyagi",
    designation: "Technical Support Engineer",
    email: "tyagi787@gmail.com",
    phone: "9917044020",
  },
  {
    id: 93,
    location: "Nanpara",
    name: "Sanjeet Maurya",
    designation: "Technical Support Engineer",
    email: "sanjeetmaurya6@gmail.com",
    phone: "8707700784",
  },
  {
    id: 94,
    location: "Nazibabad",
    name: "Navneet Kumar Chauhan",
    designation: "Technical Support Engineer",
    email: "navneet.chauhan5@gmail.com",
    phone: "8006413804",
  },
  {
    id: 95,
    location: "Noida",
    name: "Luv Kulshreshtha",
    designation: "Technical Support Engineer",
    email: "lkulshrestha5@gmail.com",
    phone: "7906212462",
  },
  {
    id: 96,
    location: "Orai",
    name: "Mohan Singh Rathaur",
    designation: "Technical Support Engineer",
    email: "mohansrathaur1011@gmail.com",
    phone: "7398711306",
  },
  {
    id: 97,
    location: "Paliya Kalan",
    name: "Jitendera Kumar",
    designation: "Technical Support Engineer",
    email: "jitendramishra69@gmail.com",
    phone: "8853199309",
  },
  {
    id: 98,
    location: "Pillibhit",
    name: "Papinder Singh",
    designation: "Technical Support Engineer",
    email: "papinder56sandhu@gmail.com",
    phone: "9837704104",
  },
  {
    id: 99,
    location: "Pratapgarh",
    name: "Navneet Kumar",
    designation: "Technical Support Engineer",
    email: "nvnt562@gmail.com",
    phone: "8005382523",
  },
  {
    id: 100,
    location: "Prayagraj",
    name: "Akhilesh Kumar",
    designation: "Technical Support Engineer",
    email: "akhileshkumar246@gmail.com",
    phone: "8299064188",
  },
  {
    id: 101,
    location: "Raibareilly",
    name: "Apurb Kumar Gupta",
    designation: "Technical Support Engineer",
    email: "apurb.ec1014@gmail.com",
    phone: "9454513314",
  },
  {
    id: 102,
    location: "Rampur",
    name: "Nalin Singh",
    designation: "Technical Support Engineer",
    email: "nalinsingh7@gmail.com",
    phone: "8630258736",
  },
  {
    id: 103,
    location: "Sambhal",
    name: "Prabhakar Yadav",
    designation: "Technical Support Engineer",
    email: "prabhakaryadav64@gmail.com",
    phone: "8077298095",
  },
  {
    id: 104,
    location: "Santkabirnagar",
    name: "Ravindra Kumar Srivastava",
    designation: "Technical Support Engineer",
    email: "ravindra269@gmail.com",
    phone: "9198137742",
  },
  {
    id: 105,
    location: "Shaharanpur",
    name: "Keshav Geol",
    designation: "Technical Support Engineer",
    email: "0008keshavgoel@gmail.com",
    phone: "8979297446",
  },
  {
    id: 106,
    location: "Shahjahanpur",
    name: "Rachit Kumar Gupta",
    designation: "Technical Support Engineer",
    email: "rachit.gupta2009@yahoo.com",
    phone: "8960149474",
  },
  {
    id: 107,
    location: "Shamli",
    name: "Digvijay Sharma",
    designation: "Technical Support Engineer",
    email: "digvijaysharma1987@gmail.com",
    phone: "9870670530",
  },
  {
    id: 108,
    location: "Shrawasti",
    name: "Shekhar Sahai",
    designation: "Technical Support Engineer",
    email: "shekhar.1571987@gmail.com",
    phone: "9140504460",
  },
  {
    id: 109,
    location: "Sidharthnagar",
    name: "Avinash Sharma",
    designation: "Technical Support Engineer",
    email: "aavinashsharma88@gmail.com",
    phone: "9839024534",
  },
  {
    id: 110,
    location: "Sitapur",
    name: "Sumit Kumar Mathur",
    designation: "Technical Support Engineer",
    email: "s.k.mathur0711@gmail.com",
    phone: "8299060229",
  },
  {
    id: 111,
    location: "Sonbhadra",
    name: "Vijyendra Kumar",
    designation: "Technical Support Engineer",
    email: "88vds1001@gmail.com",
    phone: "9452875076",
  },
  {
    id: 112,
    location: "Sultanpur",
    name: "Mukesh Tiwari",
    designation: "Technical Support Engineer",
    email: "tiwarimukesh1355@gmail.com",
    phone: "8953222633",
  },
  {
    id: 113,
    location: "Unnao",
    name: "Avinash Singh Chauhan",
    designation: "Technical Support Engineer",
    email: "avin1980@gmail.com",
    phone: "9451540864",
  },
  {
    id: 114,
    location: "Varanasi",
    name: "Md Jauher Mumtaz",
    designation: "Technical Support Engineer",
    email: "jauherkt@gmail.com",
    phone: "7905716604",
  },
];
